/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_baidu_flume_runtime_spark_impl_FlumePartitioner__ */

#ifndef _Included_com_baidu_flume_runtime_spark_impl_FlumePartitioner__
#define _Included_com_baidu_flume_runtime_spark_impl_FlumePartitioner__
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_baidu_flume_runtime_spark_impl_FlumePartitioner__
 * Method:    jniGetPartition
 * Signature: ([B)I
 */
JNIEXPORT jint JNICALL Java_com_baidu_flume_runtime_spark_impl_FlumePartitioner_00024_jniGetPartition
  (JNIEnv *, jobject, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
