/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_baidu_flume_runtime_spark_impl_jni_FlumeFilterBeforeRepartition__ */

#ifndef _Included_com_baidu_flume_runtime_spark_impl_jni_FlumeFilterBeforeRepartition__
#define _Included_com_baidu_flume_runtime_spark_impl_jni_FlumeFilterBeforeRepartition__
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_baidu_flume_runtime_spark_impl_jni_FlumeFilterBeforeRepartition__
 * Method:    jniFilteRDDData
 * Signature: (I[I[B[B)Z
 */
JNIEXPORT jboolean JNICALL Java_com_baidu_flume_runtime_spark_impl_jni_FlumeFilterBeforeRepartition_00024_jniFilteRDDData
  (JNIEnv *, jobject, jint, jintArray, jbyteArray, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
