/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_baidu_flume_runtime_spark_impl_jni_FlumeTask__ */

#ifndef _Included_com_baidu_flume_runtime_spark_impl_jni_FlumeTask__
#define _Included_com_baidu_flume_runtime_spark_impl_jni_FlumeTask__
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_baidu_flume_runtime_spark_impl_jni_FlumeTask__
 * Method:    jniBuildTask
 * Signature: ([BI)J
 */
JNIEXPORT jlong JNICALL Java_com_baidu_flume_runtime_spark_impl_jni_FlumeTask_00024_jniBuildTask
  (JNIEnv *, jobject, jbyteArray, jbyteArray, jint);

/*
 * Class:     com_baidu_flume_runtime_spark_impl_jni_FlumeTask__
 * Method:    jniReleaseTask
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_baidu_flume_runtime_spark_impl_jni_FlumeTask_00024_jniReleaseTask
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_baidu_flume_runtime_spark_impl_jni_FlumeTask__
 * Method:    jniGetOutputBufferPtr
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_baidu_flume_runtime_spark_impl_jni_FlumeTask_00024_jniGetOutputBufferPtr
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_baidu_flume_runtime_spark_impl_jni_FlumeTask__
 * Method:    jniRun
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_baidu_flume_runtime_spark_impl_jni_FlumeTask_00024_jniRun
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     com_baidu_flume_runtime_spark_impl_jni_FlumeTask__
 * Method:    jniProcessInput
 * Signature: (J[BI[BI)V
 */
JNIEXPORT void JNICALL Java_com_baidu_flume_runtime_spark_impl_jni_FlumeTask_00024_jniProcessInput
  (JNIEnv *, jobject, jlong, jbyteArray, jint, jbyteArray, jint);

/*
 * Class:     com_baidu_flume_runtime_spark_impl_jni_FlumeTask__
 * Method:    jniProcessKey
 * Signature: (J[BI)V
 */
JNIEXPORT void JNICALL Java_com_baidu_flume_runtime_spark_impl_jni_FlumeTask_00024_jniProcessKey
  (JNIEnv *, jobject, jlong, jbyteArray, jint);

/*
 * Class:     com_baidu_flume_runtime_spark_impl_jni_FlumeTask__
 * Method:    jniProcessValue
 * Signature: (J[BI)V
 */
JNIEXPORT void JNICALL Java_com_baidu_flume_runtime_spark_impl_jni_FlumeTask_00024_jniProcessValue
  (JNIEnv *, jobject, jlong, jbyteArray, jint);

/*
 * Class:     com_baidu_flume_runtime_spark_impl_jni_FlumeTask__
 * Method:    jniInputDone
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_baidu_flume_runtime_spark_impl_jni_FlumeTask_00024_jniInputDone
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
