/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_baidu_flume_runtime_spark_impl_jni_KVBuffer__ */

#ifndef _Included_com_baidu_flume_runtime_spark_impl_jni_KVBuffer__
#define _Included_com_baidu_flume_runtime_spark_impl_jni_KVBuffer__
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_baidu_flume_runtime_spark_impl_jni_KVBuffer__
 * Method:    jniReset
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_baidu_flume_runtime_spark_impl_jni_KVBuffer_00024_jniReset
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_baidu_flume_runtime_spark_impl_jni_KVBuffer__
 * Method:    jniNext
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_baidu_flume_runtime_spark_impl_jni_KVBuffer_00024_jniNext
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_baidu_flume_runtime_spark_impl_jni_KVBuffer__
 * Method:    jniHasNext
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_com_baidu_flume_runtime_spark_impl_jni_KVBuffer_00024_jniHasNext
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_baidu_flume_runtime_spark_impl_jni_KVBuffer__
 * Method:    jniKey
 * Signature: (J)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_baidu_flume_runtime_spark_impl_jni_KVBuffer_00024_jniKey
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_baidu_flume_runtime_spark_impl_jni_KVBuffer__
 * Method:    jniValue
 * Signature: (J)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_baidu_flume_runtime_spark_impl_jni_KVBuffer_00024_jniValue
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
