SET(toft_src
  ./storage/file/file.h
  ./storage/file/file.cpp
  ./storage/file/local_file.h
  ./storage/file/local_file.cpp
  ./storage/file/uri_utils.cpp
  ./storage/file/mock_file.cpp
  ./storage/file/mock_file.h
  ./storage/file/hdfs_file.cpp
  ./storage/seqfile/local_sequence_file_reader.cpp
  ./storage/seqfile/local_sequence_file_writer.cpp)

SET(toft_other_src
  ./base/arena.cpp
  ./base/binary_version.cpp
  ./base/class_registry/class_registry.cpp
  ./base/closure.cpp
  ./base/int128.cpp
  ./base/random.cpp
  ./base/setup_binary_version.cpp
  ./base/static_resource.cpp
  ./base/string/algorithm.cpp
  ./base/string/compare.cpp
  ./base/string/concat.cpp
  ./base/string/format/print.cpp
  ./base/string/format/print_arg.cpp
  ./base/string/format/print_targets.cpp
  ./base/string/format/scan.cpp
  ./base/string/format/scan_arg.cpp
  ./base/string/format/specification.cpp
  ./base/string/format/vprint.cpp
  ./base/string/format/vscan.cpp
  ./base/string/number.cpp
  ./base/string/string_piece.cpp
  ./base/uint32_divisor.cpp
  ./compress/block/block_compression.cpp
  ./compress/block/snappy.cpp
  ./container/bitmap.cpp
  ./container/bloom_filter.cpp
  ./crypto/hash/md5.cpp
  ./crypto/hash/sha1.cpp
  ./crypto/uuid/uuid.cpp
  ./encoding/ascii.cpp
  ./encoding/hex.cpp
  ./encoding/percent.cpp
  ./encoding/shell.cpp
  ./encoding/varint.cpp
  ./hash/city.cpp
  ./hash/crc32.cpp
  ./hash/fingerprint32.cpp
  ./hash/fingerprint64.cpp
  ./hash/jenkins.cpp
  ./hash/murmur/MurmurHash2.cpp
  ./hash/murmur/MurmurHash2_64.cpp
  ./hash/murmur/MurmurHash2A.cpp
  ./hash/murmur/MurmurHash3.cpp
  ./hash/murmur/MurmurHashAligned2.cpp
  ./hash/murmur/MurmurHashNeutral2.cpp
  ./hash/super_fast.cpp
  ./net/http/client.cpp
  ./net/http/headers.cpp
  ./net/http/message.cpp
  ./net/http/request.cpp
  ./net/http/response.cpp
  ./net/http/server/connection.cpp
  ./net/http/server/handler.cpp
  ./net/http/server/server.cpp
  ./net/http/time.cpp
  ./net/mime/mime.cpp
  ./net/uri/query_params.cpp
  ./net/uri/uri.cpp
  ./storage/path/path.cpp
  ./storage/sstable/hfile/block.cpp
  ./storage/sstable/hfile/coding.cpp
  ./storage/sstable/hfile/data_block.cpp
  ./storage/sstable/hfile/data_index.cpp
  ./storage/sstable/hfile/file_info.cpp
  ./storage/sstable/hfile/file_trailer.cpp
  ./storage/sstable/reader/in_memory_sstable_reader.cpp
  ./storage/sstable/reader/merged_sstable_reader.cpp
  ./storage/sstable/reader/on_disk_sstable_reader.cpp
  ./storage/sstable/reader/sstable_reader.cpp
  ./storage/sstable/reader/sstable_reader_impl.cpp
  ./storage/sstable/reader/sstable_reader_iterator.cpp
  ./storage/sstable/writer/base_sstable_writer.cpp
  ./storage/sstable/writer/composited_sstable_writer.cpp
  ./storage/sstable/writer/sharding_sstable_writer.cpp
  ./storage/sstable/writer/single_sstable_writer.cpp
  ./storage/sstable/writer/unsorted_sstable_writer.cpp
  ./system/atomic/atomic.cpp
  ./system/check_error.cpp
  ./system/event_dispatcher/event_dispatcher.cpp
  ./system/info/info.cpp
  ./system/net/domain_resolver.cpp
  ./system/net/ip_address.cpp
  ./system/net/socket.cpp
  ./system/net/socket_address.cpp
  ./system/process/process_local_const.cpp
  ./system/process/sub_process.cpp
  ./system/process/this_process.cpp
  ./system/threading/base_thread.cpp
  ./system/threading/condition_variable.cpp
  ./system/threading/event.cpp
  ./system/threading/mutex.cpp
  ./system/threading/this_thread.cpp
  ./system/threading/thread.cpp
  ./system/threading/thread_group.cpp
  ./system/threading/thread_pool.cpp
  ./system/threading/thread_types.cpp
  ./system/time/timestamp.cpp
  ./system/time/clock.cpp
  ./system/time/date.cpp
  ./system/time/posix_time.cpp
  ./text/wildcard.cpp
  ./base/arena.h
  ./base/array_size.h
  ./base/binary_version.h
  ./base/class_registry/class_registry.h
  ./base/class_registry.h
  ./base/closure.h
  ./base/cxx11.h
  ./base/functional.h
  ./base/int128.h
  ./base/intrusive_list.h
  ./base/linking_assert.h
  ./base/preprocess/disallow_in_header.h
  ./base/preprocess/join.h
  ./base/preprocess/stringize.h
  ./base/preprocess/varargs.h
  ./base/preprocess.h
  ./base/random.h
  ./base/scoped_array.h
  ./base/scoped_ptr.h
  ./base/shared_ptr.h
  ./base/singleton.h
  ./base/static_assert.h
  ./base/static_class.h
  ./base/static_resource.h
  ./base/stl_util.h
  ./base/string/algorithm.h
  ./base/string/append_1.h
  ./base/string/byte_set.h
  ./base/string/compare.h
  ./base/string/concat.h
  ./base/string/format/print.h
  ./base/string/format/print_arg.h
  ./base/string/format/print_target.h
  ./base/string/format/print_targets.h
  ./base/string/format/scan.h
  ./base/string/format/scan_arg.h
  ./base/string/format/specification.h
  ./base/string/format/vprint.h
  ./base/string/format/vscan.h
  ./base/string/format.h
  ./base/string/number.h
  ./base/string/string_piece.h
  ./base/type_cast.h
  ./base/type_traits/add_missing.h
  ./base/type_traits/conditional.h
  ./base/type_traits/enable_if.h
  ./base/type_traits/is_class.h
  ./base/type_traits/make_signness.h
  ./base/type_traits/missing.h
  ./base/type_traits/remove.h
  ./base/type_traits/std.h
  ./base/type_traits/tr1.h
  ./base/type_traits.h
  ./base/uint32_divisor.h
  ./base/uncopyable.h
  ./base/unique_ptr.h
  ./base/unordered_map.h
  ./base/unordered_set.h
  ./compress/block/block_compression.h
  ./compress/block/snappy.h
  ./container/bitmap.h
  ./container/bloom_filter.h
  ./container/lru_cache.h
  ./container/skiplist.h
  ./crypto/hash/md5.h
  ./crypto/hash/sha1.h
  ./crypto/uuid/uuid.h
  ./encoding/ascii.h
  ./encoding/hex.h
  ./encoding/percent.h
  ./encoding/shell.h
  ./encoding/varint.h
  ./hash/city.h
  ./hash/crc32.h
  ./hash/fingerprint.h
  ./hash/hash.h
  ./hash/jenkins.h
  ./hash/murmur.h
  ./hash/super_fast.h
  ./net/http/client.h
  ./net/http/headers.h
  ./net/http/message.h
  ./net/http/request.h
  ./net/http/response.h
  ./net/http/server/connection.h
  ./net/http/server/handler.h
  ./net/http/server/server.h
  ./net/http/time.h
  ./net/http/version.h
  ./net/mime/mime.h
  ./net/uri/query_params.h
  ./net/uri/uri.h
  ./storage/path/path.h
  ./storage/recordio/recordio.h
  ./storage/recordio/reverse_recordio.h
  ./storage/sharding/fingerprint_sharding.h
  ./storage/sharding/fingerprint_sharding.cc
  ./storage/sharding/sharding.h
  ./storage/sharding/sharding.cc
  ./storage/sstable/hfile/block.h
  ./storage/sstable/hfile/coding.h
  ./storage/sstable/hfile/data_block.h
  ./storage/sstable/hfile/data_index.h
  ./storage/sstable/hfile/file_info.h
  ./storage/sstable/hfile/file_trailer.h
  ./storage/sstable/merged_sstable_reader.h
  ./storage/sstable/reader/in_memory_sstable_reader.h
  ./storage/sstable/reader/on_disk_sstable_reader.h
  ./storage/sstable/reader/sstable_reader_impl.h
  ./storage/sstable/sstable.h
  ./storage/sstable/sstable_reader.h
  ./storage/sstable/sstable_writer.h
  ./storage/sstable/test/test_util.h
  ./storage/sstable/types.h
  ./storage/sstable/writer/base_sstable_writer.h
  ./storage/sstable/writer/composited_sstable_writer.h
  ./storage/sstable/writer/sharding_sstable_writer.h
  ./storage/sstable/writer/single_sstable_writer.h
  ./storage/sstable/writer/unsorted_sstable_writer.h
  ./system/atomic/atomic.h
  ./system/atomic/functions.h
  ./system/atomic/type.h
  ./system/check_error.h
  ./system/eintr_ignored.h
  ./system/event_dispatcher/event_dispatcher.h
  ./system/info/info.h
  ./system/memory/barrier.h
  ./system/memory/unaligned/align_insensitive.h
  ./system/memory/unaligned/check_direct_include.h
  ./system/memory/unaligned/gcc.h
  ./system/memory/unaligned/generic.h
  ./system/memory/unaligned/msc.h
  ./system/memory/unaligned.h
  ./system/net/domain_resolver.h
  ./system/net/ip_address.h
  ./system/net/os_socket.h
  ./system/net/socket.h
  ./system/net/socket_address.h
  ./system/process/process_local_const.h
  ./system/process/sub_process.h
  ./system/process/this_process.h
  ./system/threading/base_thread.h
  ./system/threading/condition_variable.h
  ./system/threading/event.h
  ./system/threading/mutex.h
  ./system/threading/scoped_locker.h
  ./system/threading/this_thread.h
  ./system/threading/thread.h
  ./system/threading/thread_group.h
  ./system/threading/thread_pool.h
  ./system/threading/thread_types.h
  ./system/time/clock.h
  ./system/time/date.h
  ./system/time/posix_time.h
  ./text/wildcard.h)
